export type Template = {
  id: string;
  name: string;
  imagePath: string;
  description: string;
  businessTypes: string[];
};

export type Feature = {
  id: string;
  name: string;
  price: number;
  time: number;
  popularity?: number;
  description: string;
};

export type Business = {
  id: string;
  name: string;
  popularity: number;
  features: Feature[];
  description: string;
};

export type WizardSelections = {
  business: string;
  features: string[];
  template: string;
};

export const businesses: Business[] = [
  {
    id: "clinic",
    name: "Clinic",
    popularity: 10,
    description: "Healthcare management system for medical practices",
    features: [
      {
        id: "patient-portal",
        name: "Patient Portal",
        price: 50,
        time: 4,
        popularity: 8,
        description:
          "Secure patient access to medical records and appointments",
      },
      {
        id: "appointment-booking",
        name: "Appointment Booking",
        price: 30,
        time: 3,
        popularity: 10,
        description: "Online scheduling system for patients",
      },
      {
        id: "medical-records",
        name: "Medical Records",
        price: 60,
        time: 5,
        popularity: 6,
        description: "Electronic health records management",
      },
      {
        id: "prescription-management",
        name: "Prescription Management",
        price: 40,
        time: 4,
        popularity: 7,
        description: "Digital prescription writing and tracking",
      },
      {
        id: "lab-integration",
        name: "Lab Integration",
        price: 45,
        time: 4,
        popularity: 6,
        description: "Connect with laboratory systems for test results",
      },
      {
        id: "billing",
        name: "Medical Billing",
        price: 55,
        time: 5,
        popularity: 9,
        description: "Insurance and patient billing management",
      },
      {
        id: "telemedicine",
        name: "Telemedicine",
        price: 70,
        time: 6,
        popularity: 9,
        description: "Virtual consultation platform",
      },
      {
        id: "inventory-management",
        name: "Medical Inventory",
        price: 35,
        time: 3,
        popularity: 7,
        description: "Track medical supplies and equipment",
      },
      {
        id: "analytics",
        name: "Practice Analytics",
        price: 40,
        time: 4,
        popularity: 6,
        description: "Business intelligence for medical practices",
      },
      {
        id: "patient-communication",
        name: "Patient Communication",
        price: 25,
        time: 2,
        popularity: 8,
        description: "Automated reminders and notifications",
      },
    ],
  },
  {
    id: "restaurant",
    name: "Restaurant",
    popularity: 9,
    description: "Complete restaurant management solution",
    features: [
      {
        id: "pos",
        name: "Point of Sale",
        price: 45,
        time: 4,
        popularity: 9,
        description: "Modern POS system for order management",
      },
      {
        id: "inventory",
        name: "Inventory Management",
        price: 35,
        time: 3,
        popularity: 8,
        description: "Track and manage restaurant inventory",
      },
      {
        id: "online-ordering",
        name: "Online Ordering",
        price: 40,
        time: 4,
        popularity: 9,
        description: "Custom branded online ordering system",
      },
      {
        id: "reservation",
        name: "Reservation System",
        price: 30,
        time: 3,
        popularity: 7,
        description: "Table reservation and management",
      },
      {
        id: "kitchen-display",
        name: "Kitchen Display",
        price: 35,
        time: 3,
        popularity: 8,
        description: "Digital kitchen order management",
      },
      {
        id: "menu-management",
        name: "Menu Management",
        price: 25,
        time: 2,
        popularity: 7,
        description: "Digital menu creation and updates",
      },
      {
        id: "loyalty-program",
        name: "Loyalty Program",
        price: 30,
        time: 3,
        popularity: 7,
        description: "Customer rewards and loyalty tracking",
      },
      {
        id: "staff-scheduling",
        name: "Staff Scheduling",
        price: 25,
        time: 2,
        popularity: 6,
        description: "Employee shift management",
      },
      {
        id: "analytics",
        name: "Restaurant Analytics",
        price: 35,
        time: 3,
        popularity: 7,
        description: "Business performance tracking",
      },
      {
        id: "delivery-management",
        name: "Delivery Management",
        price: 40,
        time: 4,
        popularity: 8,
        description: "Delivery order tracking and routing",
      },
    ],
  },
  {
    id: "retail",
    name: "Retail",
    popularity: 9,
    description: "Modern retail management platform",
    features: [
      {
        id: "pos",
        name: "Point of Sale",
        price: 40,
        time: 3,
        popularity: 9,
        description: "Retail POS with barcode scanning",
      },
      {
        id: "inventory",
        name: "Inventory Management",
        price: 45,
        time: 4,
        popularity: 9,
        description: "Stock tracking and management",
      },
      {
        id: "ecommerce",
        name: "E-commerce Integration",
        price: 50,
        time: 5,
        popularity: 8,
        description: "Online store with inventory sync",
      },
      {
        id: "customer-management",
        name: "Customer Management",
        price: 35,
        time: 3,
        popularity: 7,
        description: "Customer database and history",
      },
      {
        id: "loyalty-program",
        name: "Loyalty Program",
        price: 30,
        time: 3,
        popularity: 7,
        description: "Customer rewards system",
      },
      {
        id: "supplier-management",
        name: "Supplier Management",
        price: 35,
        time: 3,
        popularity: 6,
        description: "Vendor relationship management",
      },
      {
        id: "analytics",
        name: "Retail Analytics",
        price: 40,
        time: 4,
        popularity: 7,
        description: "Sales and inventory analytics",
      },
      {
        id: "employee-management",
        name: "Employee Management",
        price: 35,
        time: 3,
        popularity: 6,
        description: "Staff scheduling and performance",
      },
    ],
  },
  {
    id: "salon",
    name: "Salon",
    popularity: 8,
    description: "Salon and spa management system",
    features: [
      {
        id: "appointment-booking",
        name: "Appointment Booking",
        price: 35,
        time: 3,
        popularity: 9,
        description: "Online booking system",
      },
      {
        id: "pos",
        name: "Point of Sale",
        price: 40,
        time: 3,
        popularity: 8,
        description: "Payment processing and retail",
      },
      {
        id: "customer-management",
        name: "Customer Management",
        price: 30,
        time: 2,
        popularity: 7,
        description: "Client profiles and history",
      },
      {
        id: "inventory",
        name: "Inventory Management",
        price: 35,
        time: 3,
        popularity: 7,
        description: "Product and supply tracking",
      },
      {
        id: "staff-scheduling",
        name: "Staff Scheduling",
        price: 30,
        time: 2,
        popularity: 8,
        description: "Employee schedule management",
      },
      {
        id: "loyalty-program",
        name: "Loyalty Program",
        price: 25,
        time: 2,
        popularity: 6,
        description: "Customer rewards system",
      },
      {
        id: "marketing",
        name: "Marketing Tools",
        price: 30,
        time: 3,
        popularity: 6,
        description: "Email and SMS marketing",
      },
    ],
  },
  {
    id: "fitness",
    name: "Fitness",
    popularity: 8,
    description: "Gym and fitness center management platform",
    features: [
      {
        id: "membership-management",
        name: "Membership Management",
        price: 45,
        time: 4,
        popularity: 9,
        description: "Member profiles and subscriptions",
      },
      {
        id: "class-scheduling",
        name: "Class Scheduling",
        price: 35,
        time: 3,
        popularity: 8,
        description: "Fitness class management",
      },
      {
        id: "trainer-booking",
        name: "Trainer Booking",
        price: 30,
        time: 3,
        popularity: 7,
        description: "Personal trainer scheduling",
      },
      {
        id: "access-control",
        name: "Access Control",
        price: 40,
        time: 4,
        popularity: 8,
        description: "Member check-in system",
      },
      {
        id: "billing",
        name: "Billing Management",
        price: 35,
        time: 3,
        popularity: 7,
        description: "Payment processing",
      },
      {
        id: "equipment-tracking",
        name: "Equipment Tracking",
        price: 25,
        time: 2,
        popularity: 6,
        description: "Gym equipment management",
      },
      {
        id: "member-app",
        name: "Member Mobile App",
        price: 50,
        time: 5,
        popularity: 8,
        description: "Custom branded mobile app",
      },
    ],
  },
  {
    id: "hotel",
    name: "Hotel",
    popularity: 9,
    description: "Hotel management and booking system",
    features: [
      {
        id: "reservation",
        name: "Reservation System",
        price: 50,
        time: 5,
        popularity: 9,
        description: "Room booking management",
      },
      {
        id: "check-in",
        name: "Check-in/out System",
        price: 40,
        time: 4,
        popularity: 8,
        description: "Guest processing system",
      },
      {
        id: "housekeeping",
        name: "Housekeeping",
        price: 35,
        time: 3,
        popularity: 7,
        description: "Room maintenance tracking",
      },
      {
        id: "billing",
        name: "Billing System",
        price: 45,
        time: 4,
        popularity: 8,
        description: "Payment processing",
      },
      {
        id: "concierge",
        name: "Concierge Services",
        price: 30,
        time: 3,
        popularity: 6,
        description: "Guest service management",
      },
      {
        id: "inventory",
        name: "Inventory Management",
        price: 35,
        time: 3,
        popularity: 7,
        description: "Supply tracking system",
      },
      {
        id: "guest-app",
        name: "Guest Mobile App",
        price: 55,
        time: 5,
        popularity: 7,
        description: "Custom branded guest app",
      },
    ],
  },
  {
    id: "dental",
    name: "Dental",
    popularity: 8,
    description: "Dental practice management solution",
    features: [
      {
        id: "patient-records",
        name: "Patient Records",
        price: 50,
        time: 4,
        popularity: 9,
        description: "Digital patient files",
      },
      {
        id: "appointment-scheduling",
        name: "Appointment Scheduling",
        price: 35,
        time: 3,
        popularity: 8,
        description: "Online booking system",
      },
      {
        id: "imaging",
        name: "Imaging Integration",
        price: 60,
        time: 5,
        popularity: 8,
        description: "Digital imaging management",
      },
      {
        id: "billing",
        name: "Insurance Billing",
        price: 45,
        time: 4,
        popularity: 7,
        description: "Insurance claims processing",
      },
      {
        id: "treatment-planning",
        name: "Treatment Planning",
        price: 40,
        time: 3,
        popularity: 7,
        description: "Treatment plan management",
      },
      {
        id: "inventory",
        name: "Inventory Management",
        price: 30,
        time: 2,
        popularity: 6,
        description: "Supply tracking system",
      },
      {
        id: "patient-communication",
        name: "Patient Communication",
        price: 25,
        time: 2,
        popularity: 7,
        description: "Automated notifications",
      },
    ],
  },
  {
    id: "workshop",
    name: "Workshop",
    popularity: 7,
    description: "Auto repair shop management system",
    features: [
      {
        id: "work-orders",
        name: "Work Orders",
        price: 40,
        time: 3,
        popularity: 9,
        description: "Service ticket management",
      },
      {
        id: "appointment-scheduling",
        name: "Appointment Scheduling",
        price: 35,
        time: 3,
        popularity: 8,
        description: "Online booking system",
      },
      {
        id: "inventory",
        name: "Parts Inventory",
        price: 45,
        time: 4,
        popularity: 8,
        description: "Parts tracking system",
      },
      {
        id: "customer-management",
        name: "Customer Management",
        price: 35,
        time: 3,
        popularity: 7,
        description: "Customer relationship management",
      },
    ],
  },

  {
    id: "coffee",
    name: "Coffee",
    popularity: 8,
    description: "Café and coffee shop management platform",
    features: [
      {
        id: "pos",
        name: "Point of Sale",
        price: 35,
        time: 3,
        popularity: 9,
        description: "Café-specific POS system",
      },
      {
        id: "inventory",
        name: "Inventory Management",
        price: 30,
        time: 3,
        popularity: 8,
        description: "Coffee bean and supply tracking",
      },
      {
        id: "online-ordering",
        name: "Mobile Ordering",
        price: 40,
        time: 4,
        popularity: 9,
        description: "Mobile app ordering system",
      },
      {
        id: "loyalty",
        name: "Loyalty Program",
        price: 25,
        time: 2,
        popularity: 8,
        description: "Digital punch cards and rewards",
      },
      {
        id: "staff-scheduling",
        name: "Staff Scheduling",
        price: 20,
        time: 2,
        popularity: 7,
        description: "Barista shift management",
      },
      {
        id: "recipe-management",
        name: "Recipe Management",
        price: 25,
        time: 2,
        popularity: 7,
        description: "Drink recipe database and controls",
      },
      {
        id: "customer-display",
        name: "Customer Display",
        price: 30,
        time: 3,
        popularity: 6,
        description: "Digital menu and order status board",
      },
      {
        id: "analytics",
        name: "Sales Analytics",
        price: 35,
        time: 3,
        popularity: 7,
        description: "Business performance tracking",
      },
    ],
  },
  {
    id: "pharmacy",
    name: "Pharmacy",
    popularity: 9,
    description: "Complete pharmacy management system",
    features: [
      {
        id: "prescription-management",
        name: "Prescription Management",
        price: 65,
        time: 5,
        popularity: 10,
        description: "Digital prescription processing system",
      },
      {
        id: "inventory",
        name: "Medication Inventory",
        price: 55,
        time: 4,
        popularity: 9,
        description: "Pharmaceutical inventory control",
      },
      {
        id: "patient-records",
        name: "Patient Records",
        price: 50,
        time: 4,
        popularity: 8,
        description: "Patient history and medication tracking",
      },
      {
        id: "insurance-billing",
        name: "Insurance Billing",
        price: 45,
        time: 4,
        popularity: 8,
        description: "Insurance claim processing",
      },
      {
        id: "pos",
        name: "Point of Sale",
        price: 40,
        time: 3,
        popularity: 7,
        description: "Retail and prescription sales",
      },
      {
        id: "compliance",
        name: "Compliance Management",
        price: 60,
        time: 5,
        popularity: 9,
        description: "Regulatory compliance tracking",
      },
      {
        id: "customer-notifications",
        name: "Customer Notifications",
        price: 30,
        time: 2,
        popularity: 7,
        description: "Prescription ready alerts",
      },
      {
        id: "supplier-management",
        name: "Supplier Management",
        price: 40,
        time: 3,
        popularity: 6,
        description: "Pharmaceutical supplier coordination",
      },
    ],
  },
  {
    id: "school",
    name: "School",
    popularity: 9,
    description: "Comprehensive school management platform",
    features: [
      {
        id: "student-management",
        name: "Student Management",
        price: 55,
        time: 5,
        popularity: 9,
        description: "Student records and tracking",
      },
      {
        id: "attendance",
        name: "Attendance System",
        price: 35,
        time: 3,
        popularity: 8,
        description: "Digital attendance tracking",
      },
      {
        id: "grade-management",
        name: "Grade Management",
        price: 45,
        time: 4,
        popularity: 9,
        description: "Grading and assessment system",
      },
      {
        id: "course-scheduling",
        name: "Course Scheduling",
        price: 40,
        time: 4,
        popularity: 8,
        description: "Class schedule organization",
      },
      {
        id: "parent-portal",
        name: "Parent Portal",
        price: 50,
        time: 4,
        popularity: 8,
        description: "Parent communication platform",
      },
      {
        id: "library-management",
        name: "Library Management",
        price: 35,
        time: 3,
        popularity: 6,
        description: "Digital library system",
      },
      {
        id: "fee-management",
        name: "Fee Management",
        price: 40,
        time: 3,
        popularity: 7,
        description: "Student fee processing",
      },
      {
        id: "transportation",
        name: "Transportation Management",
        price: 35,
        time: 3,
        popularity: 6,
        description: "School bus tracking system",
      },
    ],
  },
  {
    id: "grocery",
    name: "Grocery",
    popularity: 9,
    description: "Grocery store management system",
    features: [
      {
        id: "pos",
        name: "Point of Sale",
        price: 45,
        time: 4,
        popularity: 9,
        description: "Grocery-specific POS system",
      },
      {
        id: "inventory",
        name: "Inventory Management",
        price: 50,
        time: 4,
        popularity: 9,
        description: "Perishable inventory tracking",
      },
      {
        id: "online-ordering",
        name: "Online Shopping",
        price: 55,
        time: 5,
        popularity: 8,
        description: "E-commerce platform",
      },
      {
        id: "supplier-management",
        name: "Supplier Management",
        price: 40,
        time: 3,
        popularity: 7,
        description: "Vendor relationship management",
      },
      {
        id: "loyalty",
        name: "Loyalty Program",
        price: 35,
        time: 3,
        popularity: 8,
        description: "Customer rewards system",
      },
      {
        id: "delivery-management",
        name: "Delivery Management",
        price: 45,
        time: 4,
        popularity: 8,
        description: "Delivery service coordination",
      },
      {
        id: "fresh-management",
        name: "Fresh Product Management",
        price: 40,
        time: 3,
        popularity: 7,
        description: "Produce and perishables tracking",
      },
    ],
  },
  {
    id: "supermarket",
    name: "Supermarket",
    popularity: 9,
    description: "Large-scale retail management solution",
    features: [
      {
        id: "pos",
        name: "Multi-Lane POS",
        price: 60,
        time: 5,
        popularity: 9,
        description: "Multi-checkout POS system",
      },
      {
        id: "inventory",
        name: "Advanced Inventory",
        price: 55,
        time: 5,
        popularity: 9,
        description: "Large-scale inventory management",
      },
      {
        id: "warehouse",
        name: "Warehouse Management",
        price: 50,
        time: 4,
        popularity: 8,
        description: "Warehouse operations system",
      },
      {
        id: "self-checkout",
        name: "Self-Checkout System",
        price: 65,
        time: 6,
        popularity: 8,
        description: "Automated checkout kiosks",
      },
      {
        id: "supplier-portal",
        name: "Supplier Portal",
        price: 45,
        time: 4,
        popularity: 7,
        description: "Vendor management platform",
      },
      {
        id: "loyalty",
        name: "Customer Loyalty",
        price: 40,
        time: 3,
        popularity: 8,
        description: "Rewards and membership system",
      },
      {
        id: "analytics",
        name: "Business Analytics",
        price: 50,
        time: 4,
        popularity: 7,
        description: "Advanced reporting system",
      },
    ],
  },
  {
    id: "real-estate",
    name: "Real Estate",
    popularity: 8,
    description: "Real estate agency management platform",
    features: [
      {
        id: "property-management",
        name: "Property Management",
        price: 55,
        time: 5,
        popularity: 9,
        description: "Property listing and tracking",
      },
      {
        id: "client-management",
        name: "Client Management",
        price: 45,
        time: 4,
        popularity: 8,
        description: "Client database and communication",
      },
      {
        id: "showing-scheduler",
        name: "Showing Scheduler",
        price: 35,
        time: 3,
        popularity: 8,
        description: "Property viewing coordination",
      },
      {
        id: "document-management",
        name: "Document Management",
        price: 40,
        time: 3,
        popularity: 7,
        description: "Real estate document handling",
      },
      {
        id: "marketing-tools",
        name: "Marketing Tools",
        price: 45,
        time: 4,
        popularity: 7,
        description: "Property marketing automation",
      },
      {
        id: "commission-tracking",
        name: "Commission Tracking",
        price: 35,
        time: 3,
        popularity: 6,
        description: "Agent commission management",
      },
      {
        id: "property-analytics",
        name: "Property Analytics",
        price: 50,
        time: 4,
        popularity: 7,
        description: "Market analysis tools",
      },
    ],
  },
  {
    id: "construction",
    name: "Construction",
    popularity: 8,
    description: "Construction project management system",
    features: [
      {
        id: "project-management",
        name: "Project Management",
        price: 60,
        time: 5,
        popularity: 9,
        description: "Construction project tracking",
      },
      {
        id: "resource-planning",
        name: "Resource Planning",
        price: 50,
        time: 4,
        popularity: 8,
        description: "Equipment and material planning",
      },
      {
        id: "bid-management",
        name: "Bid Management",
        price: 45,
        time: 4,
        popularity: 7,
        description: "Project bidding system",
      },
      {
        id: "safety-compliance",
        name: "Safety Compliance",
        price: 55,
        time: 5,
        popularity: 8,
        description: "Safety regulation tracking",
      },
      {
        id: "time-tracking",
        name: "Time Tracking",
        price: 35,
        time: 3,
        popularity: 7,
        description: "Worker time management",
      },
      {
        id: "document-control",
        name: "Document Control",
        price: 40,
        time: 3,
        popularity: 6,
        description: "Project documentation system",
      },
      {
        id: "equipment-management",
        name: "Equipment Management",
        price: 45,
        time: 4,
        popularity: 7,
        description: "Construction equipment tracking",
      },
    ],
  },
  {
    id: "tourism",
    name: "Tourism",
    popularity: 8,
    description: "Travel and tourism management platform",
    features: [
      {
        id: "booking-management",
        name: "Booking Management",
        price: 50,
        time: 4,
        popularity: 9,
        description: "Tour and activity booking system",
      },
      {
        id: "package-builder",
        name: "Package Builder",
        price: 45,
        time: 4,
        popularity: 8,
        description: "Custom tour package creation",
      },
      {
        id: "customer-management",
        name: "Customer Management",
        price: 40,
        time: 3,
        popularity: 7,
        description: "Tourist database and profiles",
      },
      {
        id: "payment-processing",
        name: "Payment Processing",
        price: 35,
        time: 3,
        popularity: 8,
        description: "Secure payment handling",
      },
      {
        id: "itinerary-planning",
        name: "Itinerary Planning",
        price: 40,
        time: 4,
        popularity: 7,
        description: "Travel itinerary creation",
      },
      {
        id: "partner-management",
        name: "Partner Management",
        price: 35,
        time: 3,
        popularity: 6,
        description: "Tourism partner coordination",
      },
      {
        id: "travel-docs",
        name: "Travel Documentation",
        price: 30,
        time: 2,
        popularity: 7,
        description: "Travel document management",
      },
    ],
  },
  {
    id: "law",
    name: "Law",
    popularity: 8,
    description: "Legal practice management system",
    features: [
      {
        id: "case-management",
        name: "Case Management",
        price: 65,
        time: 5,
        popularity: 9,
        description: "Legal case tracking and management",
      },
      {
        id: "document-management",
        name: "Document Management",
        price: 55,
        time: 4,
        popularity: 8,
        description: "Legal document handling",
      },
      {
        id: "time-billing",
        name: "Time & Billing",
        price: 50,
        time: 4,
        popularity: 7,
        description: "Legal billing and time tracking",
      },
    ],
  },
  {
    id: "bakery",
    name: "Bakery",
    popularity: 6,
    description: "Order and inventory system for bakeries",
    features: [
      { id: "online-ordering", name: "Online Ordering", price: 35, time: 3, popularity: 8, description: "Take orders online" },
      { id: "loyalty-program", name: "Loyalty Program", price: 25, time: 2, popularity: 7, description: "Reward repeat customers" },
      { id: "inventory", name: "Inventory", price: 30, time: 3, popularity: 6, description: "Track ingredients and stock" },
    ],
  },
  {
    id: "barbershop",
    name: "Barbershop",
    popularity: 5,
    description: "Booking and POS for barbershops",
    features: [
      { id: "online-booking", name: "Online Booking", price: 30, time: 3, popularity: 9, description: "Let clients book a chair" },
      { id: "pos", name: "Point of Sale", price: 35, time: 3, popularity: 7, description: "Checkout and payments" },
      { id: "loyalty-program", name: "Loyalty Program", price: 25, time: 2, popularity: 6, description: "Reward returning clients" },
    ],
  },
  {
    id: "spa",
    name: "Spa",
    popularity: 6,
    description: "Wellness booking and memberships",
    features: [
      { id: "online-booking", name: "Online Booking", price: 35, time: 3, popularity: 9, description: "Book treatments online" },
      { id: "memberships", name: "Memberships", price: 40, time: 4, popularity: 7, description: "Recurring membership plans" },
      { id: "pos", name: "Point of Sale", price: 35, time: 3, popularity: 6, description: "In-spa checkout" },
    ],
  },
  {
    id: "bar",
    name: "Bar",
    popularity: 5,
    description: "POS and reservations for bars",
    features: [
      { id: "pos", name: "Point of Sale", price: 40, time: 4, popularity: 9, description: "Tab and order management" },
      { id: "table-reservations", name: "Table Reservations", price: 30, time: 3, popularity: 7, description: "Reserve tables online" },
      { id: "inventory", name: "Inventory", price: 30, time: 3, popularity: 6, description: "Track stock and pours" },
    ],
  },
  {
    id: "bookstore",
    name: "Bookstore",
    popularity: 4,
    description: "Retail and catalog for bookstores",
    features: [
      { id: "online-store", name: "Online Store", price: 45, time: 4, popularity: 8, description: "Sell books online" },
      { id: "inventory", name: "Inventory", price: 30, time: 3, popularity: 7, description: "Catalog and stock" },
      { id: "pos", name: "Point of Sale", price: 35, time: 3, popularity: 6, description: "In-store checkout" },
    ],
  },
  {
    id: "florist",
    name: "Florist",
    popularity: 4,
    description: "Online flower shop and delivery",
    features: [
      { id: "online-store", name: "Online Store", price: 45, time: 4, popularity: 8, description: "Sell arrangements online" },
      { id: "delivery-tracking", name: "Delivery Tracking", price: 35, time: 3, popularity: 7, description: "Track flower deliveries" },
      { id: "inventory", name: "Inventory", price: 30, time: 3, popularity: 5, description: "Track fresh stock" },
    ],
  },
  {
    id: "photography",
    name: "Photography",
    popularity: 5,
    description: "Bookings and galleries for photographers",
    features: [
      { id: "online-booking", name: "Online Booking", price: 30, time: 3, popularity: 8, description: "Book sessions online" },
      { id: "client-gallery", name: "Client Gallery", price: 45, time: 4, popularity: 8, description: "Share and sell photos" },
      { id: "invoicing", name: "Invoicing", price: 30, time: 2, popularity: 6, description: "Send invoices to clients" },
    ],
  },
  {
    id: "veterinary",
    name: "Veterinary",
    popularity: 6,
    description: "Practice management for vet clinics",
    features: [
      { id: "appointments", name: "Appointments", price: 35, time: 3, popularity: 9, description: "Schedule pet visits" },
      { id: "pet-records", name: "Pet Records", price: 50, time: 4, popularity: 8, description: "Medical history per pet" },
      { id: "billing", name: "Billing", price: 40, time: 3, popularity: 6, description: "Invoice pet owners" },
    ],
  },
  {
    id: "laundry",
    name: "Laundry",
    popularity: 3,
    description: "Order tracking for laundry services",
    features: [
      { id: "order-tracking", name: "Order Tracking", price: 30, time: 3, popularity: 8, description: "Track wash orders" },
      { id: "pickup-delivery", name: "Pickup & Delivery", price: 35, time: 3, popularity: 7, description: "Schedule pickups" },
      { id: "pos", name: "Point of Sale", price: 30, time: 2, popularity: 5, description: "Counter checkout" },
    ],
  },
  {
    id: "travel-agency",
    name: "Travel Agency",
    popularity: 6,
    description: "Trip booking and itineraries",
    features: [
      { id: "trip-booking", name: "Trip Booking", price: 55, time: 5, popularity: 9, description: "Book flights and stays" },
      { id: "itinerary-builder", name: "Itinerary Builder", price: 40, time: 4, popularity: 7, description: "Plan day-by-day trips" },
      { id: "payments", name: "Payments", price: 35, time: 3, popularity: 7, description: "Collect deposits and payments" },
    ],
  },
  {
    id: "car-rental",
    name: "Car Rental",
    popularity: 6,
    description: "Fleet booking and management",
    features: [
      { id: "fleet-management", name: "Fleet Management", price: 55, time: 5, popularity: 8, description: "Manage vehicles" },
      { id: "online-booking", name: "Online Booking", price: 40, time: 4, popularity: 9, description: "Reserve cars online" },
      { id: "payments", name: "Payments", price: 35, time: 3, popularity: 7, description: "Deposits and charges" },
    ],
  },
  {
    id: "event-planning",
    name: "Event Planning",
    popularity: 5,
    description: "Bookings and vendors for events",
    features: [
      { id: "event-booking", name: "Event Booking", price: 45, time: 4, popularity: 8, description: "Book and manage events" },
      { id: "vendor-management", name: "Vendor Management", price: 40, time: 4, popularity: 7, description: "Coordinate vendors" },
      { id: "invoicing", name: "Invoicing", price: 30, time: 2, popularity: 6, description: "Bill clients" },
    ],
  },
  {
    id: "accounting",
    name: "Accounting",
    popularity: 6,
    description: "Bookkeeping for accounting firms",
    features: [
      { id: "invoicing", name: "Invoicing", price: 40, time: 3, popularity: 9, description: "Create and send invoices" },
      { id: "expense-tracking", name: "Expense Tracking", price: 35, time: 3, popularity: 8, description: "Log and categorize expenses" },
      { id: "financial-reports", name: "Financial Reports", price: 50, time: 4, popularity: 7, description: "Generate statements" },
    ],
  },
  {
    id: "insurance",
    name: "Insurance",
    popularity: 6,
    description: "Policy and claims management",
    features: [
      { id: "policy-management", name: "Policy Management", price: 60, time: 5, popularity: 8, description: "Manage policies" },
      { id: "claims-processing", name: "Claims Processing", price: 55, time: 5, popularity: 8, description: "Process claims" },
      { id: "crm", name: "CRM", price: 40, time: 4, popularity: 7, description: "Manage clients" },
    ],
  },
  {
    id: "logistics",
    name: "Logistics",
    popularity: 5,
    description: "Shipment and fleet tracking",
    features: [
      { id: "shipment-tracking", name: "Shipment Tracking", price: 55, time: 5, popularity: 9, description: "Track shipments" },
      { id: "fleet-management", name: "Fleet Management", price: 50, time: 5, popularity: 7, description: "Manage vehicles" },
      { id: "route-planning", name: "Route Planning", price: 45, time: 4, popularity: 7, description: "Optimize routes" },
    ],
  },
  {
    id: "nonprofit",
    name: "Nonprofit",
    popularity: 4,
    description: "Donations and volunteer management",
    features: [
      { id: "donations", name: "Donations", price: 40, time: 4, popularity: 9, description: "Collect donations online" },
      { id: "volunteer-management", name: "Volunteer Management", price: 35, time: 3, popularity: 7, description: "Coordinate volunteers" },
      { id: "event-management", name: "Event Management", price: 35, time: 3, popularity: 6, description: "Run fundraising events" },
    ],
  },
  {
    id: "daycare",
    name: "Daycare",
    popularity: 5,
    description: "Enrollment and parent communication",
    features: [
      { id: "enrollment", name: "Enrollment", price: 40, time: 4, popularity: 8, description: "Register children" },
      { id: "attendance-tracking", name: "Attendance Tracking", price: 30, time: 3, popularity: 7, description: "Daily check-in/out" },
      { id: "parent-portal", name: "Parent Portal", price: 45, time: 4, popularity: 7, description: "Updates for parents" },
    ],
  },
  {
    id: "cinema",
    name: "Cinema",
    popularity: 4,
    description: "Ticketing and showtimes",
    features: [
      { id: "ticketing", name: "Ticketing", price: 50, time: 4, popularity: 9, description: "Sell tickets online" },
      { id: "showtime-scheduling", name: "Showtime Scheduling", price: 35, time: 3, popularity: 7, description: "Schedule screenings" },
      { id: "concessions", name: "Concessions", price: 30, time: 3, popularity: 6, description: "Snack bar orders" },
    ],
  },
  {
    id: "auto-repair",
    name: "Auto Repair",
    popularity: 7,
    description: "Service scheduling and repair tracking for auto shops",
    features: [
      { id: "service-scheduling", name: "Service Scheduling", price: 40, time: 4, popularity: 9, description: "Book repair appointments" },
      { id: "vehicle-history", name: "Vehicle History", price: 35, time: 3, popularity: 7, description: "Track repairs per vehicle" },
      { id: "parts-inventory", name: "Parts Inventory", price: 45, time: 4, popularity: 7, description: "Manage parts stock" },
    ],
  },
  {
    id: "car-wash",
    name: "Car Wash",
    popularity: 6,
    description: "Memberships and bay scheduling for car washes",
    features: [
      { id: "memberships", name: "Memberships", price: 35, time: 3, popularity: 8, description: "Recurring wash plans" },
      { id: "online-booking", name: "Online Booking", price: 30, time: 3, popularity: 7, description: "Reserve a wash slot" },
      { id: "loyalty", name: "Loyalty Rewards", price: 25, time: 2, popularity: 6, description: "Points for repeat customers" },
    ],
  },
  {
    id: "gas-station",
    name: "Gas Station",
    popularity: 6,
    description: "Fuel pricing and convenience store management",
    features: [
      { id: "fuel-pricing", name: "Fuel Pricing", price: 40, time: 4, popularity: 8, description: "Manage pump prices" },
      { id: "store-pos", name: "Store POS", price: 40, time: 4, popularity: 7, description: "Sell convenience goods" },
      { id: "fuel-rewards", name: "Fuel Rewards", price: 30, time: 3, popularity: 6, description: "Reward frequent drivers" },
    ],
  },
  {
    id: "pet-store",
    name: "Pet Store",
    popularity: 6,
    description: "Inventory and grooming bookings for pet shops",
    features: [
      { id: "inventory", name: "Inventory", price: 35, time: 3, popularity: 8, description: "Track pet supplies" },
      { id: "grooming-booking", name: "Grooming Booking", price: 35, time: 3, popularity: 7, description: "Schedule grooming" },
      { id: "online-store", name: "Online Store", price: 45, time: 4, popularity: 7, description: "Sell pet products online" },
    ],
  },
  {
    id: "jewelry",
    name: "Jewelry",
    popularity: 6,
    description: "Catalog and custom orders for jewelers",
    features: [
      { id: "catalog", name: "Catalog", price: 45, time: 4, popularity: 8, description: "Showcase collections" },
      { id: "custom-orders", name: "Custom Orders", price: 50, time: 5, popularity: 7, description: "Bespoke piece requests" },
      { id: "appraisals", name: "Appraisals", price: 40, time: 4, popularity: 6, description: "Value and certify items" },
    ],
  },
  {
    id: "electronics",
    name: "Electronics",
    popularity: 7,
    description: "Inventory and repair tickets for electronics retailers",
    features: [
      { id: "inventory", name: "Inventory", price: 40, time: 4, popularity: 8, description: "Track device stock" },
      { id: "repair-tickets", name: "Repair Tickets", price: 40, time: 4, popularity: 7, description: "Manage repair jobs" },
      { id: "warranty", name: "Warranty Tracking", price: 35, time: 3, popularity: 6, description: "Track product warranties" },
    ],
  },
  {
    id: "furniture",
    name: "Furniture",
    popularity: 6,
    description: "Catalog and delivery scheduling for furniture stores",
    features: [
      { id: "catalog", name: "Catalog", price: 45, time: 4, popularity: 8, description: "Browse furniture lines" },
      { id: "delivery-scheduling", name: "Delivery Scheduling", price: 40, time: 4, popularity: 7, description: "Plan deliveries" },
      { id: "financing", name: "Financing", price: 40, time: 4, popularity: 6, description: "Installment plans" },
    ],
  },
  {
    id: "boutique",
    name: "Boutique",
    popularity: 6,
    description: "Lookbooks and online store for fashion boutiques",
    features: [
      { id: "lookbook", name: "Lookbook", price: 35, time: 3, popularity: 8, description: "Seasonal collections" },
      { id: "online-store", name: "Online Store", price: 45, time: 4, popularity: 8, description: "Sell apparel online" },
      { id: "loyalty", name: "Loyalty", price: 25, time: 2, popularity: 6, description: "Reward shoppers" },
    ],
  },
  {
    id: "shoe-store",
    name: "Shoe Store",
    popularity: 5,
    description: "Inventory and sizing for footwear retailers",
    features: [
      { id: "inventory", name: "Inventory", price: 35, time: 3, popularity: 8, description: "Track sizes and stock" },
      { id: "online-store", name: "Online Store", price: 45, time: 4, popularity: 7, description: "Sell footwear online" },
      { id: "loyalty", name: "Loyalty", price: 25, time: 2, popularity: 6, description: "Reward repeat buyers" },
    ],
  },
  {
    id: "toy-store",
    name: "Toy Store",
    popularity: 5,
    description: "Catalog and gift registries for toy shops",
    features: [
      { id: "catalog", name: "Catalog", price: 35, time: 3, popularity: 7, description: "Browse toys by age" },
      { id: "gift-registry", name: "Gift Registry", price: 30, time: 3, popularity: 6, description: "Birthday wishlists" },
      { id: "online-store", name: "Online Store", price: 45, time: 4, popularity: 7, description: "Sell toys online" },
    ],
  },
  {
    id: "hardware",
    name: "Hardware",
    popularity: 6,
    description: "Inventory and contractor accounts for hardware stores",
    features: [
      { id: "inventory", name: "Inventory", price: 40, time: 4, popularity: 8, description: "Track tools and materials" },
      { id: "contractor-accounts", name: "Contractor Accounts", price: 40, time: 4, popularity: 7, description: "Trade pricing" },
      { id: "online-store", name: "Online Store", price: 45, time: 4, popularity: 6, description: "Sell hardware online" },
    ],
  },
  {
    id: "garden-center",
    name: "Garden Center",
    popularity: 5,
    description: "Plant catalog and care guides for nurseries",
    features: [
      { id: "plant-catalog", name: "Plant Catalog", price: 35, time: 3, popularity: 7, description: "Browse plants" },
      { id: "care-guides", name: "Care Guides", price: 25, time: 2, popularity: 6, description: "Plant care tips" },
      { id: "online-store", name: "Online Store", price: 45, time: 4, popularity: 6, description: "Sell plants online" },
    ],
  },
  {
    id: "butcher",
    name: "Butcher",
    popularity: 5,
    description: "Custom cuts and orders for butcher shops",
    features: [
      { id: "custom-orders", name: "Custom Orders", price: 35, time: 3, popularity: 7, description: "Special cut requests" },
      { id: "online-ordering", name: "Online Ordering", price: 40, time: 4, popularity: 7, description: "Order meat online" },
      { id: "subscriptions", name: "Meat Subscriptions", price: 35, time: 3, popularity: 6, description: "Recurring boxes" },
    ],
  },
  {
    id: "winery",
    name: "Winery",
    popularity: 6,
    description: "Tastings and wine club for wineries",
    features: [
      { id: "tasting-booking", name: "Tasting Booking", price: 40, time: 4, popularity: 8, description: "Reserve tastings" },
      { id: "wine-club", name: "Wine Club", price: 45, time: 4, popularity: 7, description: "Membership shipments" },
      { id: "online-store", name: "Online Store", price: 45, time: 4, popularity: 7, description: "Sell bottles online" },
    ],
  },
  {
    id: "brewery",
    name: "Brewery",
    popularity: 6,
    description: "Taproom and events for breweries",
    features: [
      { id: "taproom-pos", name: "Taproom POS", price: 40, time: 4, popularity: 8, description: "Pour and sell" },
      { id: "events", name: "Events", price: 35, time: 3, popularity: 7, description: "Host taproom events" },
      { id: "online-store", name: "Online Store", price: 45, time: 4, popularity: 6, description: "Sell merch and cans" },
    ],
  },
  {
    id: "food-truck",
    name: "Food Truck",
    popularity: 6,
    description: "Location updates and mobile ordering for food trucks",
    features: [
      { id: "location-updates", name: "Location Updates", price: 30, time: 3, popularity: 8, description: "Share daily spots" },
      { id: "mobile-ordering", name: "Mobile Ordering", price: 40, time: 4, popularity: 8, description: "Order ahead" },
      { id: "pos", name: "POS", price: 35, time: 3, popularity: 7, description: "Take payments" },
    ],
  },
  {
    id: "catering",
    name: "Catering",
    popularity: 6,
    description: "Quotes and event menus for caterers",
    features: [
      { id: "quotes", name: "Quotes", price: 40, time: 4, popularity: 8, description: "Build event quotes" },
      { id: "menu-builder", name: "Menu Builder", price: 35, time: 3, popularity: 7, description: "Custom event menus" },
      { id: "scheduling", name: "Scheduling", price: 35, time: 3, popularity: 7, description: "Plan event staffing" },
    ],
  },
  {
    id: "ice-cream",
    name: "Ice Cream",
    popularity: 5,
    description: "Flavors and loyalty for ice cream shops",
    features: [
      { id: "flavor-menu", name: "Flavor Menu", price: 25, time: 2, popularity: 7, description: "Daily flavors" },
      { id: "online-ordering", name: "Online Ordering", price: 40, time: 4, popularity: 7, description: "Order for pickup" },
      { id: "loyalty", name: "Loyalty", price: 25, time: 2, popularity: 6, description: "Scoop rewards" },
    ],
  },
  {
    id: "juice-bar",
    name: "Juice Bar",
    popularity: 5,
    description: "Menu and subscriptions for juice bars",
    features: [
      { id: "menu", name: "Menu", price: 25, time: 2, popularity: 7, description: "Build the menu" },
      { id: "subscriptions", name: "Cleanse Plans", price: 35, time: 3, popularity: 6, description: "Recurring juice plans" },
      { id: "mobile-ordering", name: "Mobile Ordering", price: 40, time: 4, popularity: 7, description: "Order ahead" },
    ],
  },
  {
    id: "nightclub",
    name: "Nightclub",
    popularity: 6,
    description: "Guest lists and ticketing for nightclubs",
    features: [
      { id: "guest-list", name: "Guest List", price: 35, time: 3, popularity: 8, description: "Manage entry lists" },
      { id: "ticketing", name: "Event Ticketing", price: 45, time: 4, popularity: 8, description: "Sell event tickets" },
      { id: "table-booking", name: "Table Booking", price: 40, time: 4, popularity: 7, description: "Reserve VIP tables" },
    ],
  },
  {
    id: "bowling",
    name: "Bowling",
    popularity: 5,
    description: "Lane booking and leagues for bowling alleys",
    features: [
      { id: "lane-booking", name: "Lane Booking", price: 40, time: 4, popularity: 8, description: "Reserve lanes" },
      { id: "leagues", name: "Leagues", price: 35, time: 3, popularity: 6, description: "Run league play" },
      { id: "snack-pos", name: "Snack Bar POS", price: 30, time: 3, popularity: 6, description: "Food and drinks" },
    ],
  },
  {
    id: "arcade",
    name: "Arcade",
    popularity: 5,
    description: "Game cards and events for arcades",
    features: [
      { id: "game-cards", name: "Game Cards", price: 35, time: 3, popularity: 7, description: "Reloadable play cards" },
      { id: "party-booking", name: "Party Booking", price: 35, time: 3, popularity: 7, description: "Birthday parties" },
      { id: "prize-redemption", name: "Prize Redemption", price: 30, time: 3, popularity: 6, description: "Ticket prizes" },
    ],
  },
  {
    id: "dance-studio",
    name: "Dance Studio",
    popularity: 6,
    description: "Class scheduling and memberships for dance studios",
    features: [
      { id: "class-scheduling", name: "Class Scheduling", price: 40, time: 4, popularity: 8, description: "Book classes" },
      { id: "memberships", name: "Memberships", price: 35, time: 3, popularity: 7, description: "Recurring plans" },
      { id: "recital-tickets", name: "Recital Tickets", price: 35, time: 3, popularity: 6, description: "Sell show tickets" },
    ],
  },
  {
    id: "music-school",
    name: "Music School",
    popularity: 5,
    description: "Lesson booking and progress for music schools",
    features: [
      { id: "lesson-booking", name: "Lesson Booking", price: 40, time: 4, popularity: 8, description: "Schedule lessons" },
      { id: "progress-tracking", name: "Progress Tracking", price: 35, time: 3, popularity: 6, description: "Track student growth" },
      { id: "billing", name: "Billing", price: 35, time: 3, popularity: 7, description: "Tuition payments" },
    ],
  },
  {
    id: "art-gallery",
    name: "Art Gallery",
    popularity: 5,
    description: "Exhibitions and sales for art galleries",
    features: [
      { id: "exhibitions", name: "Exhibitions", price: 35, time: 3, popularity: 7, description: "Manage shows" },
      { id: "artwork-catalog", name: "Artwork Catalog", price: 40, time: 4, popularity: 7, description: "Catalog pieces" },
      { id: "online-sales", name: "Online Sales", price: 45, time: 4, popularity: 6, description: "Sell art online" },
    ],
  },
  {
    id: "tattoo",
    name: "Tattoo",
    popularity: 6,
    description: "Artist booking and deposits for tattoo studios",
    features: [
      { id: "artist-booking", name: "Artist Booking", price: 40, time: 4, popularity: 8, description: "Book by artist" },
      { id: "deposits", name: "Deposits", price: 30, time: 3, popularity: 7, description: "Collect deposits" },
      { id: "portfolio", name: "Portfolio", price: 35, time: 3, popularity: 7, description: "Showcase work" },
    ],
  },
  {
    id: "nail-salon",
    name: "Nail Salon",
    popularity: 6,
    description: "Appointments and loyalty for nail salons",
    features: [
      { id: "appointments", name: "Appointments", price: 35, time: 3, popularity: 8, description: "Book services" },
      { id: "loyalty", name: "Loyalty", price: 25, time: 2, popularity: 6, description: "Reward regulars" },
      { id: "online-payments", name: "Online Payments", price: 35, time: 3, popularity: 7, description: "Pay online" },
    ],
  },
  {
    id: "massage",
    name: "Massage",
    popularity: 6,
    description: "Booking and packages for massage therapists",
    features: [
      { id: "booking", name: "Booking", price: 35, time: 3, popularity: 8, description: "Schedule sessions" },
      { id: "packages", name: "Packages", price: 35, time: 3, popularity: 7, description: "Session bundles" },
      { id: "intake-forms", name: "Intake Forms", price: 30, time: 3, popularity: 6, description: "Health intake" },
    ],
  },
  {
    id: "optical",
    name: "Optical",
    popularity: 6,
    description: "Eye exams and frames for optical shops",
    features: [
      { id: "exam-booking", name: "Exam Booking", price: 40, time: 4, popularity: 8, description: "Schedule eye exams" },
      { id: "frame-catalog", name: "Frame Catalog", price: 35, time: 3, popularity: 7, description: "Browse frames" },
      { id: "insurance-billing", name: "Insurance Billing", price: 45, time: 4, popularity: 7, description: "Bill vision plans" },
    ],
  },
  {
    id: "chiropractic",
    name: "Chiropractic",
    popularity: 6,
    description: "Appointments and records for chiropractors",
    features: [
      { id: "appointments", name: "Appointments", price: 40, time: 4, popularity: 8, description: "Book adjustments" },
      { id: "patient-records", name: "Patient Records", price: 45, time: 4, popularity: 7, description: "Treatment history" },
      { id: "billing", name: "Billing", price: 40, time: 4, popularity: 7, description: "Insurance billing" },
    ],
  },
  {
    id: "physiotherapy",
    name: "Physiotherapy",
    popularity: 6,
    description: "Treatment plans and scheduling for PT clinics",
    features: [
      { id: "scheduling", name: "Scheduling", price: 40, time: 4, popularity: 8, description: "Book sessions" },
      { id: "treatment-plans", name: "Treatment Plans", price: 45, time: 4, popularity: 7, description: "Track recovery" },
      { id: "billing", name: "Billing", price: 40, time: 4, popularity: 7, description: "Insurance billing" },
    ],
  },
  {
    id: "counseling",
    name: "Counseling",
    popularity: 6,
    description: "Sessions and notes for mental health practices",
    features: [
      { id: "session-booking", name: "Session Booking", price: 40, time: 4, popularity: 8, description: "Schedule sessions" },
      { id: "teletherapy", name: "Teletherapy", price: 50, time: 5, popularity: 8, description: "Virtual sessions" },
      { id: "notes", name: "Clinical Notes", price: 40, time: 4, popularity: 6, description: "Secure session notes" },
    ],
  },
  {
    id: "nursing-home",
    name: "Nursing Home",
    popularity: 5,
    description: "Care plans and family updates for care homes",
    features: [
      { id: "care-plans", name: "Care Plans", price: 50, time: 5, popularity: 7, description: "Resident care plans" },
      { id: "family-portal", name: "Family Portal", price: 40, time: 4, popularity: 7, description: "Updates for families" },
      { id: "medication", name: "Medication Tracking", price: 45, time: 4, popularity: 6, description: "Track medications" },
    ],
  },
  {
    id: "tutoring",
    name: "Tutoring",
    popularity: 6,
    description: "Session booking and progress for tutoring centers",
    features: [
      { id: "session-booking", name: "Session Booking", price: 40, time: 4, popularity: 8, description: "Book tutors" },
      { id: "progress-tracking", name: "Progress Tracking", price: 35, time: 3, popularity: 7, description: "Track learning" },
      { id: "billing", name: "Billing", price: 35, time: 3, popularity: 7, description: "Parent billing" },
    ],
  },
  {
    id: "driving-school",
    name: "Driving School",
    popularity: 5,
    description: "Lesson scheduling and tests for driving schools",
    features: [
      { id: "lesson-scheduling", name: "Lesson Scheduling", price: 40, time: 4, popularity: 8, description: "Book lessons" },
      { id: "instructor-management", name: "Instructor Management", price: 35, time: 3, popularity: 6, description: "Assign instructors" },
      { id: "progress", name: "Progress Tracking", price: 30, time: 3, popularity: 6, description: "Track readiness" },
    ],
  },
  {
    id: "coworking",
    name: "Coworking",
    popularity: 6,
    description: "Memberships and room booking for coworking spaces",
    features: [
      { id: "memberships", name: "Memberships", price: 40, time: 4, popularity: 8, description: "Recurring desk plans" },
      { id: "room-booking", name: "Room Booking", price: 40, time: 4, popularity: 8, description: "Reserve meeting rooms" },
      { id: "access-control", name: "Access Control", price: 45, time: 4, popularity: 6, description: "Door access" },
    ],
  },
  {
    id: "marketing-agency",
    name: "Marketing Agency",
    popularity: 6,
    description: "Campaigns and reporting for marketing agencies",
    features: [
      { id: "campaign-management", name: "Campaign Management", price: 50, time: 5, popularity: 8, description: "Run campaigns" },
      { id: "client-reporting", name: "Client Reporting", price: 40, time: 4, popularity: 7, description: "Performance reports" },
      { id: "invoicing", name: "Invoicing", price: 35, time: 3, popularity: 7, description: "Bill retainers" },
    ],
  },
  {
    id: "software",
    name: "Software",
    popularity: 7,
    description: "Projects and support for software companies",
    features: [
      { id: "project-management", name: "Project Management", price: 50, time: 5, popularity: 8, description: "Track builds" },
      { id: "support-tickets", name: "Support Tickets", price: 45, time: 4, popularity: 8, description: "Customer support" },
      { id: "billing", name: "Subscription Billing", price: 45, time: 4, popularity: 7, description: "Recurring billing" },
    ],
  },
  {
    id: "consulting",
    name: "Consulting",
    popularity: 6,
    description: "Engagements and invoicing for consultancies",
    features: [
      { id: "engagements", name: "Engagements", price: 45, time: 4, popularity: 8, description: "Manage projects" },
      { id: "time-tracking", name: "Time Tracking", price: 35, time: 3, popularity: 7, description: "Billable hours" },
      { id: "invoicing", name: "Invoicing", price: 35, time: 3, popularity: 7, description: "Client billing" },
    ],
  },
  {
    id: "architecture",
    name: "Architecture",
    popularity: 6,
    description: "Projects and proposals for architecture firms",
    features: [
      { id: "project-management", name: "Project Management", price: 50, time: 5, popularity: 8, description: "Track projects" },
      { id: "proposals", name: "Proposals", price: 40, time: 4, popularity: 7, description: "Client proposals" },
      { id: "document-management", name: "Document Management", price: 40, time: 4, popularity: 6, description: "Plans and drawings" },
    ],
  },
  {
    id: "bank",
    name: "Bank",
    popularity: 7,
    description: "Accounts and online banking for financial institutions",
    features: [
      { id: "account-management", name: "Account Management", price: 60, time: 6, popularity: 8, description: "Manage accounts" },
      { id: "online-banking", name: "Online Banking", price: 60, time: 6, popularity: 9, description: "Self-service banking" },
      { id: "loan-processing", name: "Loan Processing", price: 55, time: 5, popularity: 7, description: "Process loans" },
    ],
  },
  {
    id: "tax-service",
    name: "Tax Service",
    popularity: 6,
    description: "Filing and documents for tax preparers",
    features: [
      { id: "tax-filing", name: "Tax Filing", price: 45, time: 4, popularity: 8, description: "Prepare and file" },
      { id: "document-collection", name: "Document Collection", price: 35, time: 3, popularity: 7, description: "Gather client docs" },
      { id: "appointments", name: "Appointments", price: 35, time: 3, popularity: 6, description: "Book consultations" },
    ],
  },
  {
    id: "moving",
    name: "Moving",
    popularity: 5,
    description: "Quotes and scheduling for moving companies",
    features: [
      { id: "quotes", name: "Quotes", price: 40, time: 4, popularity: 8, description: "Estimate moves" },
      { id: "scheduling", name: "Scheduling", price: 40, time: 4, popularity: 7, description: "Plan move days" },
      { id: "inventory", name: "Inventory", price: 35, time: 3, popularity: 6, description: "Track items" },
    ],
  },
  {
    id: "storage",
    name: "Storage",
    popularity: 5,
    description: "Unit rentals and payments for storage facilities",
    features: [
      { id: "unit-rentals", name: "Unit Rentals", price: 45, time: 4, popularity: 8, description: "Rent units online" },
      { id: "payments", name: "Payments", price: 40, time: 4, popularity: 7, description: "Recurring billing" },
      { id: "access-control", name: "Access Control", price: 45, time: 4, popularity: 6, description: "Gate access" },
    ],
  },
  {
    id: "cleaning",
    name: "Cleaning",
    popularity: 6,
    description: "Booking and recurring jobs for cleaning services",
    features: [
      { id: "booking", name: "Booking", price: 35, time: 3, popularity: 8, description: "Schedule cleanings" },
      { id: "recurring-jobs", name: "Recurring Jobs", price: 35, time: 3, popularity: 7, description: "Repeat schedules" },
      { id: "invoicing", name: "Invoicing", price: 30, time: 3, popularity: 6, description: "Bill clients" },
    ],
  },
  {
    id: "landscaping",
    name: "Landscaping",
    popularity: 5,
    description: "Quotes and scheduling for landscapers",
    features: [
      { id: "quotes", name: "Quotes", price: 35, time: 3, popularity: 7, description: "Estimate jobs" },
      { id: "scheduling", name: "Scheduling", price: 35, time: 3, popularity: 7, description: "Crew scheduling" },
      { id: "recurring-jobs", name: "Recurring Jobs", price: 35, time: 3, popularity: 6, description: "Maintenance plans" },
    ],
  },
  {
    id: "plumbing",
    name: "Plumbing",
    popularity: 6,
    description: "Dispatch and invoicing for plumbing businesses",
    features: [
      { id: "dispatch", name: "Dispatch", price: 40, time: 4, popularity: 8, description: "Assign jobs" },
      { id: "quotes", name: "Quotes", price: 35, time: 3, popularity: 7, description: "Estimate work" },
      { id: "invoicing", name: "Invoicing", price: 35, time: 3, popularity: 7, description: "Bill customers" },
    ],
  },
  {
    id: "electrician",
    name: "Electrician",
    popularity: 6,
    description: "Job scheduling and invoicing for electricians",
    features: [
      { id: "scheduling", name: "Scheduling", price: 40, time: 4, popularity: 8, description: "Book jobs" },
      { id: "quotes", name: "Quotes", price: 35, time: 3, popularity: 7, description: "Estimate work" },
      { id: "invoicing", name: "Invoicing", price: 35, time: 3, popularity: 7, description: "Bill customers" },
    ],
  },
  {
    id: "hvac",
    name: "HVAC",
    popularity: 6,
    description: "Service contracts and dispatch for HVAC companies",
    features: [
      { id: "service-contracts", name: "Service Contracts", price: 45, time: 4, popularity: 8, description: "Maintenance plans" },
      { id: "dispatch", name: "Dispatch", price: 40, time: 4, popularity: 7, description: "Assign technicians" },
      { id: "invoicing", name: "Invoicing", price: 35, time: 3, popularity: 7, description: "Bill customers" },
    ],
  },
  {
    id: "interior-design",
    name: "Interior Design",
    popularity: 5,
    description: "Projects and mood boards for designers",
    features: [
      { id: "project-management", name: "Project Management", price: 45, time: 4, popularity: 7, description: "Track projects" },
      { id: "mood-boards", name: "Mood Boards", price: 35, time: 3, popularity: 7, description: "Visual concepts" },
      { id: "invoicing", name: "Invoicing", price: 35, time: 3, popularity: 6, description: "Client billing" },
    ],
  },
];

// Common add-on features available to every business, merged with each
// business's own specific features so the feature cloud is always rich.
export const commonFeatures: Feature[] = [
  { id: "mobile-app", name: "Mobile App", price: 60, time: 6, popularity: 8, description: "Native iOS and Android app" },
  { id: "online-payments", name: "Online Payments", price: 35, time: 3, popularity: 9, description: "Accept cards and digital wallets" },
  { id: "analytics-dashboard", name: "Analytics", price: 40, time: 4, popularity: 7, description: "Track your key metrics" },
  { id: "notifications", name: "Notifications", price: 25, time: 2, popularity: 7, description: "Email and SMS alerts" },
  { id: "reviews", name: "Reviews", price: 30, time: 3, popularity: 7, description: "Collect ratings and reviews" },
  { id: "loyalty-program", name: "Loyalty Program", price: 35, time: 3, popularity: 6, description: "Reward repeat customers" },
  { id: "email-marketing", name: "Email Marketing", price: 35, time: 3, popularity: 6, description: "Campaigns and newsletters" },
  { id: "customer-crm", name: "Customer CRM", price: 45, time: 4, popularity: 7, description: "Manage customer profiles" },
  { id: "multi-location", name: "Multi-location", price: 50, time: 5, popularity: 6, description: "Manage multiple branches" },
  { id: "staff-management", name: "Staff Management", price: 40, time: 4, popularity: 7, description: "Schedules and roles" },
  { id: "reporting", name: "Reports", price: 35, time: 3, popularity: 6, description: "Exportable business reports" },
  { id: "live-chat", name: "Live Chat", price: 30, time: 3, popularity: 6, description: "Chat with customers" },
  { id: "gift-cards", name: "Gift Cards", price: 30, time: 3, popularity: 5, description: "Sell digital gift cards" },
  { id: "seo", name: "SEO", price: 35, time: 3, popularity: 6, description: "Rank higher on search" },
  { id: "multilingual", name: "Multi-language", price: 30, time: 3, popularity: 6, description: "Arabic and English support" },
  { id: "integrations", name: "Integrations", price: 45, time: 4, popularity: 6, description: "Connect third-party tools" },
  { id: "admin-dashboard", name: "Admin Dashboard", price: 40, time: 4, popularity: 7, description: "Central control panel" },
  { id: "social-media", name: "Social Media", price: 30, time: 3, popularity: 6, description: "Schedule and post content" },
];

// A business's own features first (they stay most prominent), then every
// common add-on that doesn't clash by id or name.
export function getBusinessFeatures(business: Business): Feature[] {
  const ids = new Set(business.features.map((f) => f.id));
  const names = new Set(business.features.map((f) => f.name.toLowerCase()));
  return [
    ...business.features,
    ...commonFeatures.filter(
      (f) => !ids.has(f.id) && !names.has(f.name.toLowerCase())
    ),
  ];
}

export const templates: Template[] = [
  {
    id: "clinic-modern",
    name: "Modern Clinic",
    imagePath: "/templates/clinic-modern.png",
    description: "Clean and professional design for modern medical practices",
    businessTypes: ["clinic"]
  },
  {
    id: "clinic-minimal",
    name: "Classic Minimal",
    imagePath: "/templates/clinic-minimal.png",
    description: "Classic and trustworthy medical interface",
    businessTypes: ["clinic"]
  },
  {
    id: "clinic-bold",
    name: "Bold Clinic",
    imagePath: "/templates/clinic-bold.png",
    description: "Classic and trustworthy medical interface",
    businessTypes: ["clinic"]
  },
];
